# docker-compose up
# docker-compose down --rmi all
version: '3'
services:
  flask:
    build:
      context: ./src
    ports:
      - '80:80'
    depends_on:
      - node
  node:
    build:
      context: ./src/node
    ports:
      - '8080:8080'
  