# docker-compose up
# docker-compose down --rmi all
# note that only ports 80 and 8080 are internet accessible in Azure
# only image works in azure, not build
version: '3'
services:
  node:
    build:
      context: ./src/node
    ports:
      - '3000:3000'
  flask:
    build:
      context: ./src
    ports:
      - '80:80'
    depends_on:
      - node