# docker-compose up
# docker-compose down --rmi all
# note that only ports 80 and 8080 are internet accessible in Azure
# only image works in azure, not build
version: '3'
services:
  node:
    build: ./src/node
    # image: danielxdante/node:latest
    ports:
      - '3000:3000'
  flask:
    build: ./src
    # image: danielxdante/flask:latest
    ports:
      - '80:80'
    depends_on:
      - node