# docker-compose up
# docker-compose down --rmi all

version: '3'
services:
  node:
    build: ./src/node
    ports:
      - '3000:3000'
  flask:
    build: ./src
    ports:
      - '80:80'
    depends_on:
      - node