services:
  db:
    container_name: db
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password123"
      MYSQL_ROOT_HOST: localhost
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - db
