# docker-compose up
# docker-compose down --rmi all
# note that only ports 80 and 8080 are accessible in Azure
version: '3'
services:
  flask:
    build:
      context: ./src
    ports:
      - '8080:8080'
    depends_on:
      - node
  node:
    build:
      context: ./src/node
    ports:
      - '80:80'
  