db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "n%40itik1007"
      MYSQL_ROOT_HOST: localhost
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro