openapi: 3.0.0
info:
  title: Agecheckfor55WDL 
  description: |
    ### To check age eligibility for 55 WDL.
    The service shall validate member's CPF account number and Birth date.
    This service shall retrieve the following information.
    1. 55 Eligibility Tag
    2. 55A eligibility Tag
    3. Return code
    4. Return message
    
    ### Change log
    | version | Date      | Description                         |
    | ------- | --------- | ----------------------------------- |
    | 1.0.0   | 2021-10-09| First version                       |
    | 1.0.1   | 2021-12-01| change xxxxx for xxxxxxx            |
    | 1.0.2   | 2022-04-09| change xxxxx for xxxxxxx            |
    | 1.1.0   | 2022-07-04| change xxxxx for xxxxxxx            |
    | 1.1.1   | 2022-10-05| change xxxxx for xxxxxxx            |
  version: 1.1.1
  x-author: MS1
  x-date: 2023-03-01
  x-searchKeywords: 55WDL
paths:
  '/discretionaryWithdrawals/55Withdrawals/v2/checkMemberAgeEligibility':
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accountNumber:
                  type: string
                  description: Member Account Number
                  example: 'S3120874B'
                birthdate:
                  type: string
                  description: Member Birthdate (CCYY-MM-DD)
                  example: '1965-03-04'
                guid:
                  type: string
                  description: Globally Unique Identifier for data integrity check
                  example: 'abcab671-68e8-4096-8bbc-fe3e184ef72b'
              required:
                - accountNumber
                - startMonth
                - endMonth
      responses:
        200:
          description: Successfully retrieved contribution history
          content:
            application/json:
              examples:
                Return00:
                  summary: normal return 
                  value:
                    accountNumber: 'S3120874B'
                    birthdate: '1965-03-04'
                    55EligibilityTag: 'Y'
                    55AEligibilityTag: 'N'
                    returnCode: '00'
                    returnMessage: 'SUCCESSFUL'
                    guid: 'abcab671-68e8-4096-8bbc-fe3e184ef72b'
                Return01:
                  summary: error return 
                  value:
                    accountNumber: ''
                    birthdate: '1965-03-04'
                    55EligibilityTag: ''
                    55AEligibilityTag: ''
                    returnCode: '01'  
                    returnMessage: 'ACCOUNT NUMBER NOT PROVIDED'
                    guid: 'abcab671-68e8-4096-8bbc-fe3e184ef72b'
              schema:
                type: object
                properties:
                  accountNumber:
                    type: string
                    description: Member Account Number
                  birthdate:
                    type: string
                    description: Member Birthdate (CCYY-MM-DD)
                  55EligibilityTag:
                    type: string
                    enum: [Y, N]
                    description: |
                        **The below table defines the value of 55EligibilityTag**
                        | Value   | Description                         |
                        | ------- | ----------------------------------- |
                        | Y       | Eligible                            |
                        | N       | Not Eligible                        |
                  55AEligibilityTag:
                    type: string
                    enum: [N]
                    description: |
                        **The below table defines the value of 55AEligibilityTag**
                        | Value   | Description                         |
                        | ------- | ----------------------------------- |
                        | N       | Default value                       |
                  returnCode:
                    type: string
                    description: |
                        **The below table defines the value of returnCode**
                        | Value   | Description                         |
                        | ------- | ----------------------------------- |
                        | 00      | Successful                          |
                        | 01      | Account number not provided         |
                        | 02      | Member's age unknown                |
                        | 03      | Invalid birthdate - DD              |
                        | 04      | Invalid birthdate - MM              |
                        | 05      | Not a cpf member                    |
                        | 06      | invalid pensionable tag             |
                        | 07      | medisave table not found            |
                        | 08      | last withdrawal age is not valid    |
                        | 12      | Invalid birthdate - CCYY            |
                  returnMessage:
                    type: string
                    description: Return Message
                  guid:
                    type: string
                    description: Globally Unique Identifier for data integrity check
                required:
                  - accountNumber
                  - birthdate
                  - 55EligibilityTag
                  - 55AEligibilityTag
                  - returnCode
                  - returnMessage
                  - guid
      deprecated: false